/* ================================================================== *
 *                 This file is auto-generated                        *
 * This file is generated by running `pnpm generate:type-registries`. *
 * ================================================================== */

import type ServicesAppConfig from '@repo/docs/services/app-config';

export default interface ProjectServiceRegistry {
	'services/app-config': ServicesAppConfig;
	'services/appConfig': ServicesAppConfig;
}
