/* ================================================================== *
 * =============== This file is auto-generated  ===================== *
 * This file is generated by running `pnpm generate:type-registries`. *
 * ================================================================== */
import type ServicesDave from '@repo/docs/services/dave';
import type ServicesSession from '@repo/docs/services/session';

export default interface ClientServiceRegistry {
  'services/dave': ServicesDave;
  'services/session': ServicesSession;
}
