/* ================================================================== *
 *                 This file is auto-generated                        *
 * This file is generated by running `pnpm generate:type-registries`. *
 * ================================================================== */

import type ComponentsTitle from '@repo/docs/components/title';

export default interface ProjectComponentRegistry {
  'components/title': typeof ComponentsTitle;
  'Components::Title': typeof ComponentsTitle;
}
